# Generate api_key using ruby -e "require 'securerandom'; p SecureRandom.hex"
---
name: frontend
api_key: 707bc29143e5f590bb1d71540f1631db
---
name: static
api_key: 3e67cd55e8da19269de9b3849f5dcf47
---
name: feedback
api_key: 1a2997c4d9cb6ffbbe6dfdc0e9ba20de